# Generated by Django 4.1 on 2023-01-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quesmodel',
            old_name='opt1',
            new_name='op1',
        ),
        migrations.RenameField(
            model_name='quesmodel',
            old_name='opt2',
            new_name='op2',
        ),
        migrations.RenameField(
            model_name='quesmodel',
            old_name='opt3',
            new_name='op3',
        ),
        migrations.RenameField(
            model_name='quesmodel',
            old_name='opt4',
            new_name='op4',
        ),
    ]
